name: 'Otus C++ Prof homework 9 `mapreduce`'

on:
  push:
    branches:
      - master
      - feature/github_actions
  # позволяет запускать workflow вручную с вкладки actions в интерфейсе github.com
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # при выполнении задания будет доступен наш репозиторий
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
      - run: cmake --build .
      #- run: cmake --build . --target test
      - run: cmake --build . --target package
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./mapreduce-0.0.${{ github.run_number }}-Linux.deb
          asset_name: mapreduce-0.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package